// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:

        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.windows:

        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:

        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );

    }
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd3B5huM5iCxsgiG_1Z_QIdAbh_oX_RcU',
    appId: '1:508913384122:android:56a3ee710eef1e61c82083',
    messagingSenderId: '508913384122',
    projectId: 'umodzi-7e23d',
    storageBucket: 'umodzi-7e23d.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoix97-m3t5l8NsUkhzEYETl7Ox2sK04U',
    appId: '1:508913384122:ios:6190c9661f530253c82083',
    messagingSenderId: '508913384122',
    projectId: 'umodzi-7e23d',
    storageBucket: 'umodzi-7e23d.firebasestorage.app',
    iosBundleId: 'com.example.umodzi',
  );



}
